# Generated by Django 5.1.2 on 2024-10-25 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "balance_after_transaction",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("deposit", "입금"), ("withdrawal", "출금")],
                        max_length=20,
                    ),
                ),
                ("transaction_method", models.CharField(max_length=20)),
                ("transaction_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction History",
                "verbose_name_plural": "Transaction Histories",
                "db_table": "transaction_history",
                "ordering": ["-transaction_datetime"],
            },
        ),
    ]
