# Generated by Django 5.1.2 on 2024-10-29 01:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction_history", "0002_alter_transactionhistory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhistory",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
